version: '3.7'

services:
  db:
    platform: linux/x86_64
    image: mariadb:10.6.5
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
    - "${DATABASE_PORT:-3306}:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    # command: /bin/sh -c "rm -f tmp/pids/server.pid && rm -f log/development.log && bundle exec rails server -b '0.0.0.0'"
    # /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    ports:
      - ${RAILS_PORT:-3000}:3000
    volumes:
      - ./:/active-dbml
      - bundle_data:/usr/local/bundle
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  db-data:
  bundle_data:
